<?php

/**
 * @file
 * Primary module hooks for eL Abee Next.js module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_config_schema_info_alter().
 *
 * @param array[] $definitions
 *   Associative array of configuration type definitions keyed by schema type
 *   names. The elements are themselves array with information about the type.
 */
function elabee_next_config_schema_info_alter(array &$definitions): void {
  $definitions['next.next_site.*']['mapping']['deploy_hook'] = [
    'type' => 'uri',
    'label' => 'Deploy Hook',
  ];
}

/**
 * Implements hook_entity_insert().
 */
function elabee_next_entity_insert(EntityInterface $entity): void {
  /** @var \Drupal\elabee_next\DeployHook $service */
  $service = \Drupal::service('elabee_next.deploy_hook');
  $service->trigger($entity);
}

/**
 * Implements hook_entity_update().
 */
function elabee_next_entity_update(EntityInterface $entity): void {
  /** @var \Drupal\elabee_next\DeployHook $service */
  $service = \Drupal::service('elabee_next.deploy_hook');
  $service->trigger($entity);
}
